export const experience = [
  {
    id: 1,
    position: 'UI Developer, Design Systems',
    company: `Carter's`,
    location: 'Remote',
    time: 'Full-Time',
    duration: '2024–Present',
  },
  {
    id: 2,
    position: 'Senior Software Engineer II',
    company: 'Humana',
    location: 'Remote',
    time: 'Full-Time',
    duration: '2022–2024',
  },
  {
    id: 3,
    position: 'Senior Software Engineer II',
    company: 'Author by Humana',
    location: 'Remote',
    time: 'Full-Time',
    duration: '2021–2022',
  },
  {
    id: 4,
    position: 'Lead Frontend Developer',
    company: 'InterCoastal Net Designs',
    location: 'Remote',
    time: 'Full-Time',
    duration: '2017–2021',
  },
  {
    id: 5,
    position: 'UX Developer',
    company: 'Navient',
    location: 'Fishers, IN',
    time: 'Full-Time',
    duration: '2017 (contract)',
  },
  {
    id: 6,
    position: 'Frontend Developer',
    company: 'InterCoastal Net Designs',
    location: 'Remote',
    time: 'Full-Time',
    duration: '2015–2017',
  },
  {
    id: 7,
    position: 'Web Developer',
    company: 'Orbis Education',
    location: 'Indianapolis, IN',
    time: 'Full-Time',
    duration: '2014–2015',
  },
  {
    id: 8,
    position: 'Frontend Developer',
    company: 'InterCoastal Net Designs',
    location: 'Remote',
    time: 'Full-Time',
    duration: '2008–2014',
  },
  {
    id: 9,
    position: 'Creative Director',
    company: 'Marian Records',
    location: 'Nashville, TN',
    time: 'Full-Time',
    duration: '2007–2008',
  },
];
